export const kwin_compliant_keys: { [key: string]: string } = {
  // Modifier keys - canonical form with all common aliases/variants normalized
  "shift": "Shift",
  "shft": "Shift",

  "ctrl": "Control",
  "control": "Control",
  "ctl": "Control",

  "alt": "Alt",

  "meta": "Meta",
  "cmd": "Meta",
  "Cmd": "Meta",
  "command": "Meta",
  "Command": "Meta",

  // Alphabet letters - map both lowercase and uppercase to uppercase
  "a": "A",
  "A": "A",
  "b": "B",
  "B": "B",
  "c": "C",
  "C": "C",
  "d": "D",
  "D": "D",
  "e": "E",
  "E": "E",
  "f": "F",
  "F": "F",
  "g": "G",
  "G": "G",
  "h": "H",
  "H": "H",
  "i": "I",
  "I": "I",
  "j": "J",
  "J": "J",
  "k": "K",
  "K": "K",
  "l": "L",
  "L": "L",
  "m": "M",
  "M": "M",
  "n": "N",
  "N": "N",
  "o": "O",
  "O": "O",
  "p": "P",
  "P": "P",
  "q": "Q",
  "Q": "Q",
  "r": "R",
  "R": "R",
  "s": "S",
  "S": "S",
  "t": "T",
  "T": "T",
  "u": "U",
  "U": "U",
  "v": "V",
  "V": "V",
  "w": "W",
  "W": "W",
  "x": "X",
  "X": "X",
  "y": "Y",
  "Y": "Y",
  "z": "Z",
  "Z": "Z",
};
